### ISSUE TITLE
Uncompleteable contracts.

### ISSUE THREAD

**Issue by Antice** [linuxgurugamer/RoverContracts#1]
Hi. When doing the offered kerbin rovermission, the contract waypoints have the wrong names, and the task list is truncated after accepting the contract.
It's not possible to finish the contract, even tho it seems to accept the waypoints as valid.
It says I have not completed th3 science objective, despite having sendt home data.

/Antice

**Comment by linuxgurugamer** [comment]
save file, please.  Also, a list of mods, if you can.
Thanks

**Comment by Antice** [comment]
![screenshot4](https://cloud.githubusercontent.com/assets/9406502/13287531/d24549ac-db07-11e5-86ab-b28594d8af52.png)
[modlist.zip](https://github.com/linuxgurugamer/RoverContracts/files/144718/modlist.zip)
Working on the savefile, Just have to replicate the situation correctly for it to fail.

**Comment by Antice** [comment]
Science is being done, but it's not looking like it is registering it. (already got all the grasslands science earlier, so it's value is 0:
![screenshot5](https://cloud.githubusercontent.com/assets/9406502/13288351/d69408dc-db0b-11e5-9819-99fe23b512ea.png)
This is after revocering.
![screenshot6](https://cloud.githubusercontent.com/assets/9406502/13288361/e234d18a-db0b-11e5-9717-0322af2e7ab7.png)

savefile:

[persistent.zip](https://github.com/linuxgurugamer/RoverContracts/files/144767/persistent.zip)

I'm available on IRC #CKAN for the next hour or so if you have any questions.

**Comment by Antice** [comment]
Hi. I've done some more testing, and can confidently recreate this issue across multiple installs with different mod's.
This only happens on Kerbin as far as I can tell, and it's tied in with recovering a rover that has done another contract like the ones you get from field science (get science from around the KSC type). And then recover that rover.
The Rover contract given by your contract pack then seems to be bound to the no longer existing rover, and thus becomes un-completable by any new rover launched.  
The naming errors appear to just be cosmetic, since not recovering the former rover before accepting this rover contract ends in the contract completing as it should do.
I hope this helps.

**Comment by linuxgurugamer** [comment]
It does, I'm going to try to get to it this week.
Thanks

**Comment by linuxgurugamer** [comment]
There is a definite problem, I'm looking into it.

**Comment by linuxgurugamer** [comment]
if it's still happening, please reopen this
